import {
  Document,
  Page,
  View,
  Text,
  Image,
  StyleSheet,
} from "@react-pdf/renderer";
import type { AnalysisResult, DatasetSummary } from "@/types";

const CHART_TYPE_LABEL: Record<string, string> = {
  bar: "Bar chart",
  line: "Line chart",
  pie: "Pie chart",
};

const s = StyleSheet.create({
  page: {
    padding: 40,
    fontFamily: "Helvetica",
    backgroundColor: "#ffffff",
    fontSize: 10,
    color: "#18181b",
  },

  // Header
  header: {
    backgroundColor: "#6366f1",
    borderRadius: 8,
    padding: 20,
    marginBottom: 24,
  },
  headerTitle: {
    color: "#ffffff",
    fontSize: 20,
    fontFamily: "Helvetica-Bold",
    marginBottom: 4,
  },
  headerMeta: {
    color: "rgba(255,255,255,0.7)",
    fontSize: 9,
  },

  // Sections
  section: { marginBottom: 20 },
  sectionLabel: {
    fontSize: 8,
    fontFamily: "Helvetica-Bold",
    color: "#6366f1",
    textTransform: "uppercase",
    letterSpacing: 1,
    marginBottom: 8,
  },

  // Summary card
  card: {
    backgroundColor: "#f4f4f5",
    borderRadius: 6,
    padding: 12,
  },
  cardText: {
    fontSize: 10,
    color: "#27272a",
    lineHeight: 1.6,
  },

  // Two-column layout
  twoCol: { flexDirection: "row", gap: 16 },
  col: { flex: 1 },

  // Numbered list items
  listItem: { flexDirection: "row", marginBottom: 7, gap: 8 },
  listBadge: {
    width: 16,
    height: 16,
    backgroundColor: "#ede9fe",
    borderRadius: 8,
    fontSize: 8,
    fontFamily: "Helvetica-Bold",
    color: "#6366f1",
    textAlign: "center",
    paddingTop: 3,
  },
  listText: {
    flex: 1,
    fontSize: 9,
    color: "#3f3f46",
    lineHeight: 1.55,
  },

  // Chart cards
  chartCard: {
    backgroundColor: "#f4f4f5",
    borderRadius: 6,
    padding: 12,
    marginBottom: 8,
  },
  chartTitle: {
    fontSize: 10,
    fontFamily: "Helvetica-Bold",
    color: "#18181b",
    marginBottom: 3,
  },
  chartMeta: {
    fontSize: 8,
    color: "#71717a",
    marginBottom: 6,
  },
  chartInsight: {
    fontSize: 9,
    color: "#52525b",
    lineHeight: 1.5,
  },
  chartImage: {
    width: "100%",
    height: 130,
    borderRadius: 4,
    marginBottom: 6,
  },

  // Footer
  footer: {
    position: "absolute",
    bottom: 24,
    left: 40,
    right: 40,
    flexDirection: "row",
    justifyContent: "space-between",
  },
  footerText: { fontSize: 8, color: "#a1a1aa" },
});

interface ReportDocumentProps {
  result: AnalysisResult;
  dataset: DatasetSummary;
  generatedAt: string;
  chartImages?: string[];
}

export function ReportDocument({
  result,
  dataset,
  generatedAt,
  chartImages,
}: ReportDocumentProps) {
  return (
    <Document title={`Prism Report — ${dataset.fileName}`}>
      <Page size="A4" style={s.page}>
        {/* Header */}
        <View style={s.header}>
          <Text style={s.headerTitle}>Prism</Text>
          <Text style={s.headerMeta}>
            {dataset.fileName} · {dataset.rowCount.toLocaleString()} rows ·{" "}
            {dataset.columnCount} columns · {generatedAt}
          </Text>
        </View>

        {/* Summary */}
        <View style={s.section}>
          <Text style={s.sectionLabel}>Executive Summary</Text>
          <View style={s.card}>
            <Text style={s.cardText}>{result.summary}</Text>
          </View>
        </View>

        {/* Insights + Recommendations */}
        <View style={[s.section, s.twoCol]}>
          <View style={s.col}>
            <Text style={s.sectionLabel}>Key Insights</Text>
            {result.insights.map((item, i) => (
              <View key={i} style={s.listItem}>
                <Text style={s.listBadge}>{i + 1}</Text>
                <Text style={s.listText}>{item}</Text>
              </View>
            ))}
          </View>
          <View style={s.col}>
            <Text style={s.sectionLabel}>Recommendations</Text>
            {result.recommendations.map((item, i) => (
              <View key={i} style={s.listItem}>
                <Text style={s.listBadge}>{i + 1}</Text>
                <Text style={s.listText}>{item}</Text>
              </View>
            ))}
          </View>
        </View>

        {/* Charts */}
        <View style={s.section}>
          <Text style={s.sectionLabel}>Charts</Text>
          {result.charts.map((chart, i) => (
            <View key={i} style={s.chartCard}>
              <Text style={s.chartTitle}>{chart.title}</Text>
              <Text style={s.chartMeta}>
                {CHART_TYPE_LABEL[chart.type] ?? chart.type} · {chart.x_key}{" "}
                vs {chart.y_key} · {chart.data.length} data points
              </Text>
              {chartImages?.[i] ? (
                <Image src={chartImages[i]} style={s.chartImage} />
              ) : null}
              <Text style={s.chartInsight}>{chart.insight}</Text>
            </View>
          ))}
        </View>

        {/* Footer */}
        <View style={s.footer} fixed>
          <Text style={s.footerText}>Generated by Prism</Text>
          <Text
            style={s.footerText}
            render={({
              pageNumber,
              totalPages,
            }: {
              pageNumber: number;
              totalPages: number;
            }) => `${pageNumber} / ${totalPages}`}
          />
        </View>
      </Page>
    </Document>
  );
}
